services:

  webapp:
    container_name: web-app
    build : ../helloworld
    command:
      - --host=0.0.0.0
    ports:
      - 8000:8000

  linux:
    container_name: shell
    image: jonlabelle/network-tools
    command:
      - sleep
      - "1000"


